// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_R3SddYxu1vmG4sfMfxU7ONcbbzn99uo',
    appId: '1:618436312170:web:c05506f595b34c5de9de13',
    messagingSenderId: '618436312170',
    projectId: 'agrisagedatabase',
    authDomain: 'agrisagedatabase.firebaseapp.com',
    storageBucket: 'agrisagedatabase.firebasestorage.app',
    measurementId: 'G-7BQLEXVT4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxD0pa0PT5nI3YXFm_6q6H13R-5Xi5oG4',
    appId: '1:618436312170:android:106940165ffffd12e9de13',
    messagingSenderId: '618436312170',
    projectId: 'agrisagedatabase',
    storageBucket: 'agrisagedatabase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWl-ektqwFV0gj519aT5ilz6eXIwuxyZo',
    appId: '1:618436312170:ios:16c99d8460bae609e9de13',
    messagingSenderId: '618436312170',
    projectId: 'agrisagedatabase',
    storageBucket: 'agrisagedatabase.firebasestorage.app',
    androidClientId: '618436312170-jkn5665rqpi18h02va6tapvf2tueke6o.apps.googleusercontent.com',
    iosClientId: '618436312170-lp5rth09ugrudnt2cfhqp4p252ao8j0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFypApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_R3SddYxu1vmG4sfMfxU7ONcbbzn99uo',
    appId: '1:618436312170:web:059cdcd904c5f988e9de13',
    messagingSenderId: '618436312170',
    projectId: 'agrisagedatabase',
    authDomain: 'agrisagedatabase.firebaseapp.com',
    storageBucket: 'agrisagedatabase.firebasestorage.app',
    measurementId: 'G-QE757NFC1D',
  );

}